In [3]:
import numpy as np
from BOOM.opt_sfl import create_edge_server

# 创建 Edge_Server 对象
edge_training = create_edge_server()

# 使用不同的 split_points 进行评估
split_points = (3, 3, 3, 17, 12, 15,15,8,9,10)
result = edge_training.EDC(split_points)
print(result)

class EDC:

  def __init__(self, dim=10):
        self.dim = dim
        self.lb = 0 * np.ones(dim)
        self.ub = 1 * np.ones(dim)

  def __call__(self, X):

    edge_training = create_edge_server()

    split_points = [x for x in X]

    split_points = tuple(split_points[0])

    # split points is Tuple
    result = edge_training.EDC(split_points)

    return -result

f = EDC(10)

-17723.742164892064


In [ ]:
import os
os.environ['HF_TOKEN'] = "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"

from huggingface_hub import notebook_login

notebook_login(os.environ['HF_TOKEN'])

In [4]:
import numpy as np
from scipy.stats import qmc

class SobolDiscreteSampler:
    def __init__(self, dim, int_lb=3, int_ub=17):
        """初始化采样器
        dim: 维度大小
        int_lb: 离散整数的最小值
        int_ub: 离散整数的最大值
        """
        self.dim = dim
        self.int_lb = int_lb
        self.int_ub = int_ub
        self.n_values = self.int_ub - self.int_lb + 1  # 离散值的个数

    def warp_discrete(self, X):
        """将连续变量转换为 one-hot 编码"""
        X_ = np.zeros((X.shape[0], self.dim * self.n_values))  # one-hot 编码维度
        for i in range(self.dim):
            # 每个维度找到对应的离散值索引
            idx = np.clip(np.round(X[:, i] * (self.n_values - 1)), 0, self.n_values - 1).astype(int)
            for j, val in enumerate(idx):
                X_[j, i * self.n_values + val] = 1
        return X_

    def unwarp_discrete(self, X_):
        """将 one-hot 编码转换回离散整数"""
        X = np.zeros((X_.shape[0], self.dim))
        for i in range(self.dim):
            # 获取每个维度 one-hot 编码中的最大值位置，并映射回对应的离散整数
            onehot_idx = np.argmax(X_[:, i * self.n_values:(i + 1) * self.n_values], axis=1)
            X[:, i] = onehot_idx + self.int_lb  # 将 one-hot 索引转换回 [int_lb, int_ub] 的整数
        return X.astype(int)

    def generate_sobol_discrete_points(self, n_points=100):
        """生成 Sobol 序列中的连续点，并将其转换为离散整点"""
        # 生成 Sobol 序列
        sobol = qmc.Sobol(d=self.dim, scramble=False)
        X_continuous = sobol.random(n=n_points)  # 生成 n_points 个 Sobol 连续点
        
        # 使用 warp_discrete 将连续点转换为离散整点（One-hot 编码形式）
        X_discrete = self.warp_discrete(X_continuous)
        
        # 将 One-hot 编码转换回离散整数
        X_unwarped = self.unwarp_discrete(X_discrete)
        
        return X_unwarped

# 示例用法
dim = 10  # 维度大小
sampler = SobolDiscreteSampler(dim)
sobol_points = sampler.generate_sobol_discrete_points(n_points=100)
print(sobol_points)


[[ 3  3  3  3  3  3  3  3  3  3]
 [10 10 10 10 10 10 10 10 10 10]
 [13  7  7  7 13 13  7 13 13 13]
 [ 7 13 13 13  7  7 13  7  7  7]
 [ 8  8 12 15  8  5  8 15 15 12]
 [15 15  5  8 15 12 15  8  8  5]
 [12  5 15 12 12 15  5  5  5  8]
 [ 5 12  8  5  5  8 12 12 12 15]
 [ 6  7 16  9 11  7  9 16 16  7]
 [13 14  9 16  4 14 16  9  9 14]
 [16  4 13  6  7 11  6  6  6 11]
 [ 9 11  6 13 14  4 13 13 13  4]
 [ 7  6  7 11 16  9  4  4  4 16]
 [14 13 14  4  9 16 11 11 11  9]
 [11  9  4 14  6 13  7 14 14  6]
 [ 4 16 11  7 13  6 14  7  7 13]
 [ 4 10 10 12  7 17 10 15 10  5]
 [11 17 17  5 14 10  3  8 17 12]
 [15  6  6 16 10  6 14  4 13 16]
 [ 8 13 13  9  3 13  7 11  6  9]
 [10  4 15  7  5 15 16  6 11 10]
 [17 11  8 14 12  8  9 13  4  3]
 [13  8 11  3 16  4 12 17  8  7]
 [ 6 15  4 10  9 11  5 10 15 14]
 [ 5  5 10 15 15 12 17  5 10 10]
 [12 12  3  8  8  5 10 12  3 17]
 [16  9 14 11  4  9 13 16  7 13]
 [ 9 16  7  4 11 16  6  9 14  6]
 [ 7  7  5  6 13 10 11 14  9 15]
 [14 14 12 13  6  3  4  7 16  8]
 [10  3  9

/home/haotian/anaconda3/envs/llmbo/lib/python3.12/site-packages/scipy/stats/_qmc.py:958: UserWarning: The balance properties of Sobol' points require n to be a power of 2.
  sample = self._random(n, workers=workers)
